ARG ELK_VERSION

# https://github.com/elastic/kibana-docker
# FROM docker.elastic.co/kibana/kibana:${ELK_VERSION}
FROM docker.elastic.co/kibana/kibana:7.3.1

# USER root

# RUN /usr/share/kibana/bin/kibana-plugin install https://github.com/bitsensor/elastalert-kibana-plugin/releases/download/1.1.0/elastalert-kibana-plugin-1.1.0-7.4.2.zip --allow-root

# USER kibana

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>