filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/nginx/*.log

output:
  logstash:
    enabled: true
    hosts: ["logstash:5044"]
  # FIXME: Cannot reach the hosts of Logstash

logging:
  level: warning
  to_files: true
  files:
    path: /var/log/filebeat
    name: beat.log
    keepfiles: 7
    rotateeverybytes: 10485760 # 10 MB
  level: debug
  selectors: ["*"]

  # output.elasticsearch:
  #   hosts: ["http://elasticsearch:9200"]
  #   username: "elastic"
  #   password: "changeme"
  # setup.kibana:
  #   host: "http://kibana:5601"
  #   username: "elastic"
  #   password: "changeme"